version: "3.8"

services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/code/app
    depends_on:
      - db
  db:
    image: mariadb:10.5
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    env_file:
      - ./.env.development

volumes:
  data: